version: '3'

services:
  lottoland-web-client:
    container_name: lottoland-web-client
    build:
      context: .
      dockerfile: ./Dockerfile
    image: lottoland-web-client
    ports:
     - "8080:8080"
    volumes:
     - ./src:/app/src
