version: '3'

services:
  web-client:
    container_name: web-client
    build:
      context: .
      dockerfile: ./Dockerfile
    image: web-client
    ports:
     - "8080:8080"
    volumes:
     - ./src:/app/src
