name: Pull Request

on:
  pull_request:
    branches: ['**']

jobs:
  build:
    name: Build
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Lint
        if: success()
        run: yarn lint

      - name: Run Unit Tests
        if: success()
        run: yarn test

      - name: Run Build
        if: success()
        run: yarn build
